### ISSUE TITLE
[BUG] Summary issue for latest release(s) compatibility issues and regressions

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/Migaku-Kanji-Addon#139] opened 2022-01-02 03:03 UTC
Creating one issue to park reports of feature regressions and compatibility issues pertaining to the latest releases of both the Migaku Anki addon, and Migaku Browser Extension. This also coincides with a new recommendation to use the latest version of Anki `v2.1.49+`, instead of the previously recommended fixed version of `v2.1.35`.

Issues 1-3 reported by `Quist 「キスト」#0786` and `ChristopherFritz#5813`, the rest added by me:
1. ~Separate `Migaku` menu from the new all-in-one Migaku Anki addon.~
2. ~Automatic card creation (via new cards) no longer working.~
3. ~Example vocab from new cards don't appear on kanji cards, even after refresh.~
4. ~The installed addon name on AnkiWeb is "Migaku Kanji GOD" whereas the `*.ankipackage` file in this repo is just "Migaku Kanji". Other references around the repo should also be brought in line with the "_ GOD" suffix, or the naming should otherwise be made consistent via whatever consensus.~
5. Perhaps directly related to #4, users migrating to the new AnkiWeb addon don't retain their custom keywords/stories (I'd hazard a guess that this is because it appears as a new, separate addon, with a different name).
6. ~Clicking example words on desktop Anki no longer open the Migaku Dictionary, but instead open up Jisho.org; this used to be mobile-only behaviour.~
7. ~I don't think the new Migaku note types are recognised by default anymore in the Registered Fields tab, for out-of-the-box functionality.~

**Comment by ChristopherFritz** [comment] 2022-01-02 04:08
It appears the lack of aqt.mw.Exporter is responsible for at least some missing functionality.  This was defined in accentExporter.py in the Migaku Japanese add-on, but is not available in the Migaku Anki Extension add-on.  This impacts at least functions that utilize mecab.

**Comment by RicBent** [comment] 2022-01-06 22:21
Fixed/Implemented 1, 6 and 7.
2 and 3 are caused by the parser not working.

**Comment by saxoncameron** [comment] 2022-01-06 23:33
Updated the original description to cross out completed/fixed issues 👍

**Comment by saxoncameron** [comment] 2022-01-08 07:18
@RicBent what do we want to do with the one outstanding issue, 5? Should we create a separate ticket for that, and close this one? Or?

**Comment by RicBent** [comment] 2022-01-08 15:27
Did so in #149. Closing~

**Closed by RicBent** 2022-01-08 15:27 UTC
Labels: bug, python
