### ISSUE TITLE
[BUG] Error messages on a fresh start of Anki on the first deck opened

### ISSUE THREAD

**Issue by mattias** [migaku-official/Migaku-Kanji-Addon#161] opened 2022-03-07 21:00 UTC
**Describe the bug**
I start Anki, then open a deck and press "Study now" and then I get the following two error messages after one another.

First error popup displays the following information:
`Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-03-06 21:59:36

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 142, in _onCmd
  File "aqt\webview.py", line 595, in _onBridgeCmd
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\matti\AppData\Roaming\Anki2\addons21\review_heatmap\links.py", line 69, in heatmapLinkHandler
    return None if not _old else _old(self, url)
  File "aqt\overview.py", line 91, in _linkHandler
  File "aqt\main.py", line 671, in moveToState
  File "aqt\hooks_gen.py", line 3650, in __call__
  File "C:\Users\matti\AppData\Roaming\Anki2\addons21\1872210448\reviewer.py", line 63, in learn_ahead_refresh_on_review_start
    aqt.mw.migaku_kanji_db.refresh_learn_ahead()
  File "C:\Users\matti\AppData\Roaming\Anki2\addons21\1872210448\kanji.py", line 427, in refresh_learn_ahead
    self.make_cards_from_characters(ct, new, None)
  File "C:\Users\matti\AppData\Roaming\Anki2\addons21\1872210448\kanji.py", line 621, in make_cards_from_characters
    aqt.mw.requireReset()
  File "aqt\main.py", line 784, in requireReset
  File "aqt\main.py", line 769, in reset
  File "aqt\main.py", line 721, in _synthesize_op_did_execute_from_reset
  File "aqt\hooks_gen.py", line 2859, in __call__
  File "aqt\main.py", line 729, in on_operation_did_execute
  File "aqt\reviewer.py", line 179, in op_executed
  File "aqt\reviewer.py", line 161, in refresh_if_needed
  File "aqt\reviewer.py", line 207, in nextCard
AttributeError: 'Reviewer' object has no attribute '_reps'`

The second popup then shows:
`Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-03-06 21:59:36

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 207, in on_focus_changed
  File "aqt\hooks_gen.py", line 2567, in __call__
  File "aqt\main.py", line 749, in on_focus_did_change
  File "aqt\reviewer.py", line 161, in refresh_if_needed
  File "aqt\reviewer.py", line 207, in nextCard
AttributeError: 'Reviewer' object has no attribute '_reps'`

After closing the error dialog windows I can review like normal, but I have no idea what side effects this has.

**To Reproduce**
1. Start Anki
2. Open a deck
3. Press "Study now"
4. Error messages described above will show

**Expected behavior**
I do not expect any error messages.

**Desktop (please complete the following information):**
 - OS and Version: Windows 10
 - Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

**Additional context**
My routine looks like this:
1. Learn ahead card count set to 2
2. Have "New cards/day" set to 0 on the sentence deck
3. Keep learning all new kanji until empty
4. Now set "New cards/day" to 2 on the sentence deck
5. Finish the 2 two new sentence cards and repeat from step 1 on the next day

My decks are also a mix of the old note type and the new Migaku type.
But this happens on all decks, even on one that is not a Migaku-deck.

**Screenshots**

**Comment by nico202** [comment] 2023-01-21 21:28
It seems to be caused by the deck "Custom Study Session" added to "Registered Fields".  I never added it, but it already happened twice to find it there, having this problem, and removing it from the list of fields solved the issue.

**Comment by MinmoTech** [comment] 2023-06-27 13:43
This should be fixed now, if not please reopen :)

**Closed by MinmoTech** 2023-06-27 13:43 UTC
Labels: bug
