### ISSUE TITLE
[BUG] Migaku Dictionary opens, but doesn't search, when clicking vocab

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/Migaku-Kanji-Addon#104] opened 2021-11-21 02:39 UTC
From Discord user `Seandub#1210`, reported via DM:

> window pops up but still doesnt populate the word in the search

> **btw right click and search dictionary also has the same issue**

The emboldened above 👆 might indicate this isn't strictly a problem with the kanji addon. Might be solved with the all-in-one?

More info as provided by Seandub:
> Edition    Windows 10 Pro
> Version    20H2
> Installed on    ‎8/‎13/‎2020
> OS build    19042.1288
> Experience    Windows Feature Experience Pack 120.2212.3920.0
> Anki: Version 2.1.35 (84dcaa86)
> Python 3.8.0 Qt 5.14.2 PyQt 5.14.2

![image](https://user-images.githubusercontent.com/3240185/142747229-2d7fafc9-d6e9-4996-9718-4478ae957ea2.png)

What do you think @RicBent ?

**Comment by seandub89** [comment] 2021-11-21 05:44
to clarify this comment "btw right click and search dictionary also has the same issue". 

I can highlight text, right click, and select search and this works. If the intent was that simply right clicking the gray boxes without highlighting and selecting search would search the word in the dictionary, then this does not work.

**Comment by RicBent** [comment] 2021-11-21 19:36
The right click context menu is actually from the dictionary add-on which only searches text that is highlighted.

This is probably a bug caused by the dictionary add-on. However I will mark this as `wontfix` because the dictionary add-on will replaced very soon anyways.

**Closed by RicBent** 2021-11-21 19:36 UTC
Labels: bug, needs verifying, Windows OS, python

**Comment by saxoncameron** [comment] 2021-11-21 20:16
Alright, @seandub89 - let's see if your problem persists once the new dictionary addon is out. If your issue persists, we can reopen this issue and investigate further.
