### ISSUE TITLE
[BUG] Trying to automatically create kanji cards for new sentence mining entries causes an error message

### ISSUE THREAD

**Issue by Dr0dW** [migaku-official/Migaku-Kanji-Addon#121] opened 2021-12-06 08:53 UTC
Hi, I'm tried to add an entry into a deck for sentence mining and have the plugin create new kanji cards i.e. have the window pop up to highlight the new kanji as green, blue, or red, as is shown in phase 3 in this video: https://www.youtube.com/watch?v=APMYK1Aa69k&
but I get this error:

"
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-12-06 19:14:54

Caught exception:
Traceback (most recent call last):
  File "aqt\taskman.py", line 101, in _on_closures_pending
  File "aqt\taskman.py", line 71, in <lambda>
  File "aqt\taskman.py", line 90, in wrapped_done
  File "aqt\operations\__init__.py", line 117, in wrapped_done
  File "aqt\operations\__init__.py", line 133, in _fire_change_hooks_after_op_performed
AttributeError: 'NoneType' object has no attribute 'changes'
"

**Comment by saxoncameron** [comment] 2021-12-06 10:19
Hey @Dr0dW! Could you try Tools > Check Database, and see if that fixes your problem?

Otherwise, could you please give us some more information:
- What OS you're on (Windows, Linus, Mac)
- What version of Anki you're using
- What other addons you have installed (screenshot of your addons list is fine)

@RicBent looks like `aqt\taskman` related stuff is related to Anki media...?

**Comment by Dr0dW** [comment] 2021-12-07 10:16
It didn't seem to fix the problem.
I'm using Windows 10, version 21H1
I'm using Anki version 2.1.49 (dc80804a)⁩
My other addons are:

- AnkiConnect
- Multiple type fields on card for 21
- Set Font Size
- Update lookup Tags

Thanks guys :)

**Comment by MatthiasvZ** [comment] 2021-12-15 02:20
Same here (Linux), also on 2.1.49. I tried downgrading to 2.1.35, after which I couldn't reproduce it any more. Likely related. 2.1.49 in general seems to cause a lot of bugs not present in 2.1.35.

**Comment by RicBent** [comment] 2022-01-06 22:38
Duplicate of https://github.com/migaku-official/Migaku-Kanji-Addon/issues/131

Fixed with https://github.com/migaku-official/Migaku-Kanji-Addon/commit/242b7dfb0191e94cc7cb993babf08a3707ed158d

**Closed by RicBent** 2022-01-06 22:38 UTC
Labels: bug, needs verifying
