### ISSUE TITLE
[FEATURE] Allow lookup of kanji via keywords

### ISSUE THREAD

**Issue by wholesalegerbils** [migaku-official/Migaku-Kanji-Addon#138] opened 2022-01-01 15:38 UTC
Currently, there are only three ways for you to return to a kanji you've learned:  Have it show up again in Anki so you can ctrl+shift+k something that includes the kanji, know the kanji well enough to search via the kanji itself with the "Kanji Lookup" tool, or look at the big list in your kanji stats.  There are many times when I will get a kanji wrong and think that it looks very similar to another Kanji I know but be unable to find it quickly because I don't know any vocab with that kanji in it well enough to "produce" it.  

Normally, you would be able to search through a card's attributes through the traditional Anki browse function but most of this data is not available due to the way Migaku Anki God has its cards setup.  Would it be possible to add a function that allows you to search through your Kanji cards based on any of the following attributes:

**- Keywords**

**- Keywords (primitive only)** 

**- Meanings**

As well as allowing one to search through known kanji only.

**Comment by fw42** [comment] 2022-01-01 16:00
Just storing the card data as JSON (instead of base64 encoded JSON) would just make this work out of the box (via the Anki Browser), wouldn't it?

**Comment by saxoncameron** [comment] 2022-01-01 21:27
This looks like a duplicate of #60 - which is on our roadmap as part of the next major release.
Thank you for the added context though, I'll update the original issue :)

**Closed by saxoncameron** 2022-01-01 21:27 UTC
Labels: new feature, requires discussion, idea
