### ISSUE TITLE
[BUG] No Updates Found

### ISSUE THREAD

**Issue by p0ker-fACE** [migaku-official/Migaku-Kanji-Addon#177] opened 2023-02-25 23:39 UTC
**Describe the bug**
A pop-up saying "No Updates Found" appears when attempting installing an addon or updating an installed one.

**To Reproduce**
1. Go to 'Tools>Add-ons>Get Add-ons...'
2. In the Code bar -> the code of an add-on
3. Press "OK"
4. See a pop-up saying "No Updates Found"

or 

1. Go to 'Tools>Add-ons>Check for Updates
2. See a pop-up saying "No Updates Found"

**Expected behavior**
Installing a new add-on or updating an installed one.

**Desktop**
 - OS and Version: Windows 11
 - Anki Version: 2.1.51

**Additional context**
When I disable this add-on add-on installation or add-on updates work normally.

**Comment by MinmoTech** [comment] 2023-06-08 07:36
Duplicate of https://github.com/migaku-official/Migaku-Kanji-Addon/issues/164

We will work on this soon

**Closed by MinmoTech** 2023-06-08 07:36 UTC
Labels: bug
